### ISSUE TITLE
CSS repetitions

### ISSUE THREAD

**Issue by KaanKalmi** [Jason2426/connect-your-tribe-profile-card#4]
```css
.birthday {
    background-color: var(--secondary-bg-color);
    border-radius: var(--standard-border-radius);
    margin: var(--section-spacing);
    padding: var(--primary-spacing);
}
.socials {
    background-color: var(--secondary-bg-color);
    border-radius: var(--standard-border-radius);
    margin: var(--section-spacing);
    padding: var(--primary-spacing);
}
.oneliner {
    background-color: var(--secondary-bg-color);
    border-radius: var(--standard-border-radius);
    margin: var(--section-spacing);
}
...
```
Dit kan allemaal bij elkaar als:
```css
.birthday, .socials, .oneliner, ...{
    background-color: var(--secondary-bg-color);
    border-radius: var(--standard-border-radius);
    margin: var(--section-spacing);
    padding: var(--primary-spacing);
}
````

Dit zorgt er ook voor dat je CSS bestand kleiner is en sneller ingeladen word!
